<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Extensios\**" />
    <Compile Remove="Repositories\IRepository.cs" />
    <Compile Remove="Repositories\Repository.cs" />
    <Compile Remove="Repositories\TransactionService.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Extensios\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Extensios\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Extensios\**" />
  </ItemGroup>

</Project>
